/*
 * Copyright 2015 Rockchip Electronics Co. LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __RK_MPI_H__
#define __RK_MPI_H__

/**
 * @addtogroup rk_mpi
 * @brief Rockchip Media Process Interface
 * @details Media Process Platform(MPP) provides application programming
 *          interface for the application layer, by which applications can
 *          call hardware encode and decode. Current MPP fully supports
 *          chipset RK3288/RK3228/RK3229/RK3399/RK3328/RV1108. Old chipset
 *          like RK29xx/RK30xx/RK31XX/RK3368 is partly supported due to lack
 *          of some hardware register generation module.
 *
 * [中文] Rockchip 媒体处理接口
 *        MPP 为应用层提供硬件编解码的编程接口。
 *        完整支持 RK3288/RK3228/RK3229/RK3399/RK3328/RV1108 等芯片。
 *        RK29xx/RK30xx/RK31XX/RK3368 等旧芯片因缺少部分硬件寄存器模块，仅部分支持。
 */

#include "rk_mpi_cmd.h"
#include "mpp_task.h"

/**
 * @ingroup rk_mpi
 * @brief MPP main work function set
 * @details all api function are seperated into two sets: data io api set
 *          and control api set
 *
 * (1). the data api set is for data input/output flow including:
 *
 * (1.1) simple data api set:
 *
 * decode   : both send video stream packet to decoder and get video frame from
 *            decoder at the same time.
 *
 * encode   : both send video frame to encoder and get encoded video stream from
 *            encoder at the same time.
 *
 * decode_put_packet: send video stream packet to decoder only, async interface
 *
 * decode_get_frame : get video frame from decoder only, async interface
 *
 * encode_put_frame : send video frame to encoder only, async interface
 *
 * encode_get_packet: get encoded video packet from encoder only, async interface
 *
 * (1.2) advanced task api set:
 *
 * poll     : poll port for dequeue
 *
 * dequeue  : pop a task from mpp task queue
 *
 * enqueue  : push a task to mpp task queue
 *
 * (2). the control api set is for mpp context control including:
 *
 * control  : similiar to ioctl in kernel driver, setup or get mpp internal parameter
 *
 * reset    : clear all data in mpp context, discard all packet and frame,
 *            reset all components to initialized status
 *
 * [中文] MppApi 函数指针集合 —— MPP 的全部操作接口
 *
 * 所有 API 分为两大类：
 *
 * (1) 数据流接口 —— 负责编解码数据的输入和输出：
 *
 *   (1.1) 简单接口（推荐大多数场景使用）：
 *     decode            : 同步解码 —— 送入码流 packet，同时取出解码帧 frame
 *     encode            : 同步编码 —— 送入原始帧 frame，同时取出码流 packet
 *     decode_put_packet : 异步送入码流（只送不取）
 *     decode_get_frame  : 异步取出解码帧（只取不送）
 *     encode_put_frame  : 异步送入原始帧（只送不取）
 *     encode_get_packet : 异步取出编码码流（只取不送）
 *
 *   (1.2) 高级 Task 接口（精确控制 buffer 绑定，JPEG 等场景使用）：
 *     poll    : 查询端口是否有可用的 task
 *     dequeue : 从 task 队列中取出一个 task
 *     enqueue : 把 task 送回队列
 *
 * (2) 控制接口 —— 负责参数配置和状态管理：
 *     control : 类似内核驱动的 ioctl，设置或获取 MPP 内部参数
 *     reset   : 清空所有数据，丢弃所有 packet 和 frame，重置到初始状态
 */
typedef struct MppApi_t {
    /**
     * @brief size of struct MppApi
     * [中文] MppApi 结构体的大小（字节），用于版本兼容性校验
     */
    RK_U32  size;
    /**
     * @brief mpp api version, generated by Git
     * [中文] MPI 接口版本号，由 Git 自动生成
     */
    RK_U32  version;

    // simple data flow interface | 简单数据流接口
    /**
     * @brief both send video stream packet to decoder and get video frame from
     *        decoder at the same time
     *        中文：同步解码 —— 同时送入码流并取出解码帧，一次调用完成送数据+取结果
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] packet The input video stream, its usage can refer mpp_packet.h.
     *                   中文：输入的码流数据包，用法参见 mpp_packet.h
     * @param[out] frame The output picture, its usage can refer mpp_frame.h.
     *                   中文：输出的解码图像帧，用法参见 mpp_frame.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功，负值表示失败。返回值为错误码，详见 mpp_err.h
     */
    MPP_RET (*decode)(MppCtx ctx, MppPacket packet, MppFrame *frame);
    /**
     * @brief send video stream packet to decoder only, async interface
     *        中文：异步送入码流 —— 把码流 packet 送入解码器内部队列，不等待解码结果。
     *              队列满时返回失败，需稍后重试。通常与 decode_get_frame 配对使用。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] packet The input video stream, its usage can refer mpp_packet.h.
     *                   中文：输入的码流数据包，用法参见 mpp_packet.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功（packet 已入队），负值表示失败（如队列满）
     */
    MPP_RET (*decode_put_packet)(MppCtx ctx, MppPacket packet);
    /**
     * @brief get video frame from decoder only, async interface
     *        中文：异步取出解码帧 —— 从解码器取一帧解码结果。
     *              返回的 frame 可能是正常图像帧、info_change 帧、或 NULL（无可用帧）。
     *              使用完毕后必须调用 mpp_frame_deinit 释放。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[out] frame The output picture, its usage can refer mpp_frame.h.
     *                   中文：输出的解码图像帧指针，解码器会填入帧数据，用法参见 mpp_frame.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功，负值表示失败。frame 为 NULL 时表示当前无可用帧
     */
    MPP_RET (*decode_get_frame)(MppCtx ctx, MppFrame *frame);
    /**
     * @brief both send video frame to encoder and get encoded video stream from
     *        encoder at the same time
     *        中文：同步编码 —— 同时送入原始帧并取出编码后的码流，一次调用完成送帧+取码流
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] frame The input video data, its usage can refer mpp_frame.h.
     *                  中文：输入的原始图像帧（YUV 数据），用法参见 mpp_frame.h
     * @param[out] packet The output compressed data, its usage can refer mpp_packet.h.
     *                    中文：输出的编码码流数据包，用法参见 mpp_packet.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功，负值表示失败。返回值为错误码，详见 mpp_err.h
     */
    MPP_RET (*encode)(MppCtx ctx, MppFrame frame, MppPacket *packet);
    /**
     * @brief send video frame to encoder only, async interface
     *        中文：异步送入原始帧 —— 把 YUV 帧送入编码器内部队列，不等待编码结果。
     *              通常与 encode_get_packet 配对使用。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] frame The input video data, its usage can refer mpp_frame.h.
     *                  中文：输入的原始图像帧（YUV 数据），用法参见 mpp_frame.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功（frame 已入队），负值表示失败
     */
    MPP_RET (*encode_put_frame)(MppCtx ctx, MppFrame frame);
    /**
     * @brief get encoded video packet from encoder only, async interface
     *        中文：异步取出编码码流 —— 从编码器取出一包编码后的压缩数据。
     *             取到的 packet 包含 H.264/H.265 NALU 等数据，用完须调用 mpp_packet_deinit 释放。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *               中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[out] packet The output compressed data, its usage can refer mpp_packet.h.
     *                    中文：输出的编码码流数据包指针，编码器会填入压缩数据，用法参见 mpp_packet.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功，负值表示失败。packet 为 NULL 时表示当前无可用码流
     */
    MPP_RET (*encode_get_packet)(MppCtx ctx, MppPacket *packet);

    /**
     * @brief ISP interface, will be supported in the future.
     *        中文：ISP 同步图像处理接口，暂未实现，预留给未来扩展。
     */
    MPP_RET (*isp)(MppCtx ctx, MppFrame dst, MppFrame src);
    /**
     * @brief ISP interface, will be supported in the future.
     *        中文：ISP 异步送帧接口，暂未实现。
     */
    MPP_RET (*isp_put_frame)(MppCtx ctx, MppFrame frame);
    /**
     * @brief ISP interface, will be supported in the future.
     *        中文：ISP 异步取帧接口，暂未实现。
     */
    MPP_RET (*isp_get_frame)(MppCtx ctx, MppFrame *frame);

    // advance data flow interface | 高级 Task 数据流接口
    /**
     * @brief poll port for dequeue
     *        中文：查询端口状态 —— 检查指定端口是否有可用的 task，返回 MPP_OK 表示可以 dequeue
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] type input port or output port which are both for data transaction
     *                 中文：端口类型，MPP_PORT_INPUT（输入端口）或 MPP_PORT_OUTPUT（输出端口）
     * @param[in] timeout mpp poll type, its usage can refer mpp_task.h.
     *                    中文：等待方式，MPP_POLL_BLOCK（阻塞）/ MPP_POLL_NON_BLOCK（非阻塞）/ 超时毫秒数
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示有可用 task，负值表示失败或超时
     */
    MPP_RET (*poll)(MppCtx ctx, MppPortType type, MppPollType timeout);
    /**
     * @brief dequeue MppTask, pop a task from mpp task queue
     *        中文：取出 Task —— 从指定端口的 task 队列中弹出一个 task。
     *              输入端口 dequeue 取出空 task 用于填入数据；输出端口 dequeue 取出已完成的 task。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] type input port or output port which are both for data transaction
     *                 中文：端口类型，MPP_PORT_INPUT（输入端口）或 MPP_PORT_OUTPUT（输出端口）
     * @param[out] task MppTask popped from mpp task queue, its usage can refer mpp_task.h.
     *                  中文：输出的 task 指针，从队列中弹出的 task，用法参见 mpp_task.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功，负值表示失败
     */
    MPP_RET (*dequeue)(MppCtx ctx, MppPortType type, MppTask *task);
    /**
     * @brief enqueue MppTask, push a task to mpp task queue
     *        中文：送回 Task —— 把 task 推入指定端口的队列。
     *              输入端口 enqueue 把填好数据的 task 送给 MPP 处理；
     *              输出端口 enqueue 把已取出结果的 task 归还，让 MPP 复用该槽位。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] type input port or output port which are both for data transaction
     *                 中文：端口类型，MPP_PORT_INPUT（输入端口）或 MPP_PORT_OUTPUT（输出端口）
     * @param[in] task MppTask which is sent to mpp for process, its usage can refer mpp_task.h.
     *                 中文：要送回的 task，用法参见 mpp_task.h
     * @return 0 and positive for success, negative for failure. The return
     *         value is an error code. For details, please refer mpp_err.h.
     *         中文：0 或正值表示成功，负值表示失败
     */
    MPP_RET (*enqueue)(MppCtx ctx, MppPortType type, MppTask task);

    // control interface | 控制接口
    /**
     * @brief discard all packet and frame, reset all component,
     *        for both decoder and encoder
     *        中文：重置 —— 丢弃所有未处理的 packet 和 frame，清空内部队列，
     *              将编解码器恢复到初始状态。通常在 seek、切换码流或销毁前调用。
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @return 0 for success, others for failure. The return value is an
     *         error code. For details, please refer mpp_err.h.
     *         中文：0 表示成功，其他值表示失败
     */
    MPP_RET (*reset)(MppCtx ctx);
    /**
     * @brief control function for mpp property setting
     *        中文：控制命令 —— 类似内核 ioctl，用于设置或获取 MPP 内部参数
     * @param[in] ctx The context of mpp, created by mpp_create() and initiated
     *                by mpp_init().
     *                中文：MPP 上下文，由 mpp_create() 创建、mpp_init() 初始化
     * @param[in] cmd The mpi command, its definition can refer rk_mpi_cmd.h.
     *                中文：控制命令枚举值，定义在 rk_mpi_cmd.h。常用的有：
     *                      MPP_DEC_SET_CFG / MPP_DEC_GET_CFG（设置/获取解码配置）
     *                      MPP_DEC_SET_EXT_BUF_GROUP（设置外部 buffer 组）
     *                      MPP_DEC_SET_INFO_CHANGE_READY（通知解码器 buffer 已就绪）
     *                      MPP_ENC_SET_CFG / MPP_ENC_GET_CFG（设置/获取编码配置）
     * @param[in,out] param The mpi command parameter
     *                      中文：命令参数，不同 cmd 对应不同类型的参数指针
     * @return 0 for success, others for failure. The return value is an
     *         error code. For details, please refer mpp_err.h.
     *         中文：0 表示成功，其他值表示失败
     */
    MPP_RET (*control)(MppCtx ctx, MpiCmd cmd, MppParam param);

    /**
     * @brief The reserved segment, may be used in the future
     * [中文] 保留字段，用于未来扩展，保证结构体大小向前兼容
     */
    RK_U32 reserv[16];
} MppApi;


#ifdef __cplusplus
extern "C" {
#endif

/**
 * @ingroup rk_mpi
 * @brief Create empty context structure and mpi function pointers.
 *        Use functions in MppApi to access mpp services.
 *        中文：创建 MPP 实例 —— 分配上下文和 API 函数指针集。
 *              这是使用 MPP 的第一步，之后通过 mpi->xxx() 调用编解码接口。
 *              使用完毕后必须调用 mpp_destroy() 释放。
 * @param[in,out] ctx pointer of the mpp context, refer to MpiImpl_t.
 *                    中文：MPP 上下文指针的指针，函数内部会分配并写入
 * @param[in,out] mpi pointer of mpi function, refer to MppApi.
 *                    中文：MPI 函数指针集的指针，函数内部会填入 MppApi 结构体地址
 * @return 0 for success, others for failure. The return value is an
 *         error code. For details, please refer mpp_err.h.
 *         中文：0 表示成功，其他值表示失败
 * @note This interface creates base flow context, all function calls
 *       are based on it.
 *       中文：此接口创建基础流程上下文，后续所有函数调用都依赖于它
 */
MPP_RET mpp_create(MppCtx *ctx, MppApi **mpi);
/**
 * @ingroup rk_mpi
 * @brief Call after mpp_create to setup mpp type and video format.
 *        This function will call internal context init function.
 *        中文：初始化 MPP 实例 —— 在 mpp_create 之后调用，指定工作模式和编码格式。
 *              必须在使用编解码接口之前调用。
 * @param[in] ctx The context of mpp, created by mpp_create().
 *                中文：MPP 上下文，由 mpp_create() 创建
 * @param[in] type specify decoder or encoder, refer to MppCtxType.
 *                 中文：工作模式，MPP_CTX_DEC（解码器）或 MPP_CTX_ENC（编码器）
 * @param[in] coding specify video compression coding, refer to MppCodingType.
 *                   中文：编码格式，如 MPP_VIDEO_CodingAVC（H.264）、MPP_VIDEO_CodingHEVC（H.265）等
 * @return 0 for success, others for failure. The return value is an
 *         error code. For details, please refer mpp_err.h.
 *         中文：0 表示成功，其他值表示失败
 */
MPP_RET mpp_init(MppCtx ctx, MppCtxType type, MppCodingType coding);
/**
 * @ingroup rk_mpi
 * @brief Destroy mpp context and free both context and mpi structure,
 *        it matches with mpp_init().
 *        中文：销毁 MPP 实例 —— 释放 ctx 和 mpi 的所有资源，与 mpp_create 配对使用。
 *              销毁前建议先调用 mpi->reset() 清空内部状态。
 * @param[in] ctx The context of mpp, created by mpp_create().
 *                中文：MPP 上下文，由 mpp_create() 创建
 * @return 0 for success, others for failure. The return value is an
 *         error code. For details, please refer mpp_err.h.
 *         中文：0 表示成功，其他值表示失败
 */
MPP_RET mpp_destroy(MppCtx ctx);
/**
 * @ingroup rk_mpi
 * @brief judge given format is supported or not by MPP.
 *        中文：检查格式支持 —— 查询当前芯片是否支持指定的编解码格式
 * @param[in] type specify decoder or encoder, refer to MppCtxType.
 *                 中文：工作模式，MPP_CTX_DEC（解码）或 MPP_CTX_ENC（编码）
 * @param[in] coding specify video compression coding, refer to MppCodingType.
 *                   中文：编码格式，如 MPP_VIDEO_CodingAVC（H.264）等
 * @return 0 for support, -1 for unsupported.
 *         中文：0 表示支持，-1 表示不支持
 */
MPP_RET mpp_check_support_format(MppCtxType type, MppCodingType coding);
/**
 * @ingroup rk_mpi
 * @brief List all formats supported by MPP
 *        中文：打印格式支持列表 —— 将当前芯片支持的所有编解码格式输出到标准输出
 * @param NULL no need to input parameter
 *             中文：无参数
 * @return No return value. This function just prints format information supported
 *         by MPP on standard output.
 *         中文：无返回值，直接打印到标准输出
 */
void    mpp_show_support_format(void);
/**
 * @brief List all color formats supported by MPP
 *        中文：打印颜色格式列表 —— 将 MPP 支持的所有像素格式（YUV/RGB 等）输出到标准输出
 * @return No return value.
 *         中文：无返回值
 */
void    mpp_show_color_format(void);

#ifdef __cplusplus
}
#endif

#endif /*__RK_MPI_H__*/
